language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./install.sh
- chmod a+x ./build.sh
install:
- ./install.sh
script:
- travis_wait ./build.sh
notifications:
  email: false
  slack: csugda:eHhYEHbXYLch9ERRRmGXwoM6
